AZURE_OPENAI_API_KEY = "8F5cUeF5F6bt9AMBtGNi5Dy8F2FDNNGcwCYHivbw5khMZ6yYuDupJQQJ99BEACYeBjFXJ3w3AAAAACOGIcf6"
AZURE_OPENAI_ENDPOINT = "https://llmwg.openai.azure.com/openai/deployments/gpt-4o/chat/completions?api-version=2025-01-01-preview"
AZURE_OPENAI_MODEL = "gpt-4o" 
AZURE_ML_ENDPOINT = "https://model0106wg-rywsu.centralus.inference.ml.azure.com/score"
AZURE_ML_API_KEY = "EmxZLCwHCMYsutSOWkR3mYgriw6uX8iknPnXe1kOAMA7x5NGmSjEJQQJ99BFAAAAAAAAAAAAINFRAZML1R0H"
